config/routes.rb
Rails.application.routes.draw do

  resources :inquilinos
  resources :inquilinos
  resources :inquilinos
  resources :mov_cajas
  resources :cajas
  resources :cajas
  resources :detalle_recibos
  resources :recibos
  resources :movimientos do
    collection do
      put :pagar
    end
  end
  resources :departamentos
  resources :contratos
  
  resources :inquilinos do
    collection do
      get :autocomplete_inquilino_nombre
    end
  end
  
  resources :edificios

  devise_for :usuario,  controllers: { sessions: "usuario/sessions", registrations: "usuario/registrations", passwords: "usuario/passwords"  }, :path_names => {:sign_in => 'login', :sign_up => 'registro', :sign_out => 'logout'}
  as :usuarios do
    get 'sign_in' => 'usuario/sessions#new', :as => :new_usuario_session_path
    get 'sign_up' => 'usuario/registrations#create', :as => :usuario_registration_path
    delete 'sign_out' => 'usuario/sessions#destroy', :as => :destroy_usuario_session_path
    get 'new' => 'usuario/sessions#destroy', :as => :new_usuario_password_path
  end

  cajaabierto = nil

  if cajaabierto != nil
    root 'contratos#index'
  else
    root 'cajas#new'
  end

end

app/models/edificio.rb
class Edificio < ActiveRecord::Base

	has_many :departamentos

	accepts_nested_attributes_for :departamentos, allow_destroy: true

	validates :nombre_edificio, presence: true
	validates :nombre_propietario, presence: true
	validates :direccion, presence: true

end

app/controllers/edificios_controller.rb
class EdificiosController < ApplicationController
  before_action :set_edificio, only: [:show, :edit, :update, :destroy]

  # GET /edificios
  # GET /edificios.json
  def index
    @edificios = Edificio.all
  end

  # GET /edificios/1
  # GET /edificios/1.json
  def show
  end

  # GET /edificios/new
  def new
    @edificio = Edificio.new
  end

  # GET /edificios/1/edit
  def edit
  end

  # POST /edificios
  # POST /edificios.json
  def create
    @edificio = Edificio.new(edificio_params)

    respond_to do |format|
      if @edificio.save
        format.html { redirect_to @edificio, notice: 'EDIFICIO CREADO CORRECTAMENTE.' }
        format.json { render :show, status: :created, location: @edificio }
      else
        format.html { render :new }
        format.json { render json: @edificio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edificios/1
  # PATCH/PUT /edificios/1.json
  def update
    respond_to do |format|
      if @edificio.update(edificio_params)
        format.html { redirect_to @edificio, notice: 'Edificio was successfully updated.' }
        format.json { render :show, status: :ok, location: @edificio }
      else
        format.html { render :edit }
        format.json { render json: @edificio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edificios/1
  # DELETE /edificios/1.json
  def destroy
    @edificio.destroy
    respond_to do |format|
      format.html { redirect_to edificios_url, notice: 'Edificio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edificio
      @edificio = Edificio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edificio_params
      params.require(:edificio).permit(:nombre_edificio, :nombre_propietario, :direccion, departamentos_attributes: [ :id, :nombre_departamento, :precio, :descripcion, :estado, :_destroy ])
    end
end

app/helpers/edificios_helper.rb
module EdificiosHelper
end

app/views/edificios/_form.html.erb
<div class="panel panel-primary ">
    <div class="panel-body">
        <%= form_for(@edificio) do |f| %>
        <% if @edificio.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@edificio.errors.count, "error") %> prohibited this edificio from being saved:</h2>
            <ul>
                <% @edificio.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <div class="field">
            <%= f.label :nombre_edificio %><br>
            <%= f.text_field :nombre_edificio, class: "form-control input-sm"%>
        </div>
        <div class="field">
            <%= f.label :nombre_propietario %><br>
            <%= f.text_field :nombre_propietario, class: "form-control input-sm"%>
        </div>
        <div class="field">
            <%= f.label :direccion %><br>
            <%= f.text_field :direccion , class: "form-control input-sm"%>
        </div>

          <div class="col-lg-12">
            <%= f.add_nested_fields_link :departamentos %>
            <%= f.nested_fields_for :departamentos , class: "btn btn-warning pull-rigth" ,  layout: :inline do |ff| %>
                <%= ff.hidden_field :id %>
                <div class="form-group col-md-3">
                  <%= ff.text_field :nombre_departamento, placeholder: 'Nombre', class: 'form-control input-sm' %>
                </div>
                <div class="form-group col-lg-3">
                  <%= ff.number_field :precio, placeholder: 'Precio', class: 'form-control input-sm' %>
                </div>
                <div class="form-group col-lg-3">
                  <%= ff.text_field :descripcion, placeholder: 'Descripcion', class: 'form-control input-sm' %>
                </div>
                <div class="form-group col-lg-2">
                  <%= ff.check_box :estado , class: "input-sm" , value:0 %>
                </div>

                <div class="form-group col-lg-1">
                <%= ff.remove_nested_fields_link 'Remover', class: "btn btn-warning pull-rigth" %>
                </div>
            <% end %>
          </div>
          <br>
          <br>

            <div class="text-left">
              <%= button_tag(type: 'submit', class: "btn btn-info btn-sm") do %>
                   CREAR EDIFICIO
              <% end %>
            </div>

          <% end %>
    </div>



</div>

app/views/edificios/edit.html.erb
<h1>Editar Edificio</h1>

<%= render 'form' %>

<%= link_to glyph(:eye_open) + 'VER', @edificio %> ||

<%= link_to glyph(:arrow_left) + ' ATRAS', edificios_path , class: "btn btn-default btn-xs"%>

app/views/edificios/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
   <div class="panel panel-primary">
      <div class="panel-heading">
         <h1 class="panel-title">Lista de Edificios </h1>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
         <table id="tabla" class="table table-bordered table-hover table-striper table-condensed" width="100%">
            <thead>
              <tr>
                  <th>Nombre del Edificio</th>
                  <th>Nombre Propietario</th>
                  <th>Dirección</th>
                  <th>Ver</th>
                  <th>Editar</th>
                  <th>Eliminar</th>
               </tr>
            </thead>
            <tbody>
               <% @edificios.each do |edificio| %>
               <tr>
                  <td><%= edificio.nombre_edificio %></td>
                  <td><%= edificio.nombre_propietario %></td>
                  <td><%= edificio.direccion %></td>
                 <td><%= link_to 'VER', edificio , class: "btn btn-info btn-xs" %></td>
                 <td><%= link_to 'EDITAR', edit_edificio_path(edificio), class: "btn btn-warning btn-xs" %></td>
                 <td><%= link_to 'ELIMINAR', edificio, method: :delete, data: { confirm: 'ESTAS SEGURO?' } , class: "btn btn-danger btn-xs" %></td>

               </tr>
               <% end %>
            </tbody>
         </table>
       </div>
      </div>
   </div>
</div>
<br>
<%= link_to 'Nuevo Edificio', new_edificio_path ,class: 'btn btn-success btn-sm pull-left' %>

app/views/edificios/new.html.erb
<h1>Nuevo Edificio</h1>

<%= render 'form' %>


<%= link_to glyph(:arrow_left) + ' ATRAS', edificios_path , class: "btn btn-default btn-xs"%>

app/views/edificios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-12">
  <div class="invoice-title">
    <h2>EDIFICIO</h2>
  </div>
  <HR>
<div class="row">
  <div class="col-lg-3 col-md-3 col-xs-12">
    <address>
        <strong>Nombre Edificio:</strong>
        <%= @edificio.nombre_edificio %>
    </address>
    </div>
      <div class="col-lg-4 col-md-3 col-xs-12">
        <address>
         <strong>Nombre Propietario:</strong>
        <%= @edificio.nombre_propietario %>
        </address>
    </div>
  <div class="col-lg-3 col-md-3 col-xs-12">
    <address>
      <strong>Direccion:</strong>
        <%= @edificio.direccion %>
    </address>
  </div>
  </div>
  </div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>DATOS DEL DEPARTAMENTO </strong></h3>
      </div>
<div class="panel-body">
  <div class="table-responsive">
  <table id="tabla" class="table table-striped table-hover" width="100%">
    <thead>
    <tr>
      <th>Nombre departamento</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Ver</th>
      <th>Editar</th>
      <th>Eliminar</th>
    </tr>
    </thead>
    <tbody>
    <% @edificio.departamentos.each do |departamento| %>
        <tr>
          <td><%= departamento.nombre_departamento %></td>
          <td><%= number_with_precision(departamento.precio, precision: 0, separator: ',', delimiter: '.') %></td>
          <td><%= departamento.descripcion %></td>
          <% if departamento.estado %>
              <td class="text-center"><label class="label label-success">OCUPADO</label></td>
          <% else %>
              <td class="text-center"><label class="label label-warning">DISPONIBLE</label></td>
          <% end %>
          <td><%= link_to 'VER', departamento , class: "btn btn-info btn-xs" %></td>
          <td><%= link_to 'EDITAR', edit_departamento_path(departamento), class: "btn btn-warning btn-xs" %></td>
          <td><%= link_to 'ELIMINAR', departamento, method: :delete, data: { confirm: 'ESTAS SEGURO?' } , class: "btn btn-danger btn-xs" %></td>

        </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>
    </div>
  </div>

  <%= link_to glyph(:pencil) +'EDITAR', edit_edificio_path(@edificio) ,class: "btn btn-warning btn-xs" %> |

<%= link_to glyph(:arrow_left) + ' ATRAS', edificio_path , class: "btn btn-default btn-xs"%>