config/routes.rb
Rails.application.routes.draw do

  resources :inquilinos
  resources :inquilinos
  resources :inquilinos
  resources :mov_cajas
  resources :cajas
  resources :cajas
  resources :detalle_recibos
  resources :recibos
  resources :movimientos do
    collection do
      put :pagar
    end
  end
  resources :departamentos
  resources :contratos
  
  resources :inquilinos do
    collection do
      get :autocomplete_inquilino_nombre
    end
  end
  
  resources :edificios

  devise_for :usuario,  controllers: { sessions: "usuario/sessions", registrations: "usuario/registrations", passwords: "usuario/passwords"  }, :path_names => {:sign_in => 'login', :sign_up => 'registro', :sign_out => 'logout'}
  as :usuarios do
    get 'sign_in' => 'usuario/sessions#new', :as => :new_usuario_session_path
    get 'sign_up' => 'usuario/registrations#create', :as => :usuario_registration_path
    delete 'sign_out' => 'usuario/sessions#destroy', :as => :destroy_usuario_session_path
    get 'new' => 'usuario/sessions#destroy', :as => :new_usuario_password_path
  end

  cajaabierto = nil

  if cajaabierto != nil
    root 'contratos#index'
  else
    root 'cajas#new'
  end

end

app/models/inquilino.rb
class Inquilino < ActiveRecord::Base

  has_many :contratos

  validates :cedula, presence: true
  validates :cedula, numericality: true
  validates :cedula, length: { maximum: 10 }

  validates :nombre, presence: true

  validates :apellido, presence: true

  validates :telefono, presence: true
  validates :telefono, numericality: true
  validates :telefono, length: { maximum: 10 }

  validates :email, presence: true

end

app/controllers/inquilinos_controller.rb
class InquilinosController < ApplicationController
  before_action :set_inquilino, only: [:show, :edit, :update, :destroy]

  # GET /inquilinos
  # GET /inquilinos.json
  def index
    @inquilinos = Inquilino.all
  end

  # GET /inquilinos/1
  # GET /inquilinos/1.json
  def show
  end

  # GET /inquilinos/new
  def new
    @inquilino = Inquilino.new
  end

  # GET /inquilinos/1/edit
  def edit
  end

  # POST /inquilinos
  # POST /inquilinos.json
  def create
    @inquilino = Inquilino.new(inquilino_params)

    respond_to do |format|
      if @inquilino.save
        format.html { redirect_to @inquilino, notice: 'INQUILINO CREADO CORRECTAMENTE.' }
        format.json { render :show, status: :created, location: @inquilino }
      else
        format.html { render :new }
        format.json { render json: @inquilino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquilinos/1
  # PATCH/PUT /inquilinos/1.json
  def update
    respond_to do |format|
      if @inquilino.update(inquilino_params)
        format.html { redirect_to @inquilino, notice: 'Inquilino was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquilino }
      else
        format.html { render :edit }
        format.json { render json: @inquilino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquilinos/1
  # DELETE /inquilinos/1.json
  def destroy
    @inquilino.destroy
    respond_to do |format|
      format.html { redirect_to inquilinos_url, notice: 'Inquilino was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquilino
      @inquilino = Inquilino.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquilino_params
      params.require(:inquilino).permit(:cedula, :nombre, :apellido, :telefono, :email, :estado)
    end
end

app/helpers/inquilinos_helper.rb
module InquilinosHelper
end

app/views/inquilinos/_form.html.erb
<div class="panel panel-primary text-uppercase">
  <div class="panel-body">
    <%= form_for(@inquilino) do |f| %>
        <% if @inquilino.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@inquilino.errors.count, "error") %> prohibited this inquilino from being saved:</h2>
              <ul>
                <% @inquilino.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="field">
          <%= f.label :cedula %><br>
          <%= f.number_field :cedula,placeholder: 'Cedula' ,class: "form-control input-sm "%>
        </div>
        <div class="field">
          <%= f.label :nombre %><br>
          <%= f.text_field :nombre, placeholder: 'Nombres ', class: "form-control input-sm"%>
        </div>
        <div class="field">
          <%= f.label :apellido %><br>
          <%= f.text_field :apellido ,placeholder: 'Apellidos', class: "form-control input-sm"%>
        </div>
        <div class="field">
          <%= f.label :telefono %><br>
          <%= f.number_field :telefono, placeholder: 'Telefono',class: "form-control input-sm"%>
        </div>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email, placeholder: 'Email', class: "form-control input-sm "%>
        </div>
        <div class="hidden">
          <%= f.label :estado %><br>
          <%= f.check_box :estado, placeholder: 'Email', class: "form-control input-sm "%>
        </div>
        <br>
        <div class="text-left">
          <%= button_tag(type: 'submit', class: "btn btn-info btn-sm") do %>
              CREAR INQUILINO
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/inquilinos/edit.html.erb
<h1>Editar Inquilino</h1>

<%= render 'form' %>


<%= link_to glyph(:eye_open) + 'VER',  @inquilino %> ||

<%= link_to glyph(:arrow_left) + ' ATRAS', inquilinos_path , class: "btn btn-default btn-xs"%>

app/views/inquilinos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="panel-title">Lista de Inquilinos</h1>
    </div>
    <div class="panel-body">
      <table id="tabla" class="table table-striped table-hover" width="100%">
        <thead>
        <tr>
          <th>Cedula</th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Telefono</th>
          <th>Email</th>
          <th>Estado</th>
          <th>Ver</th>
          <th>Editar</th>
          <th>Eliminar</th>
        </tr>
        </thead>
        <tbody>
        <% @inquilinos.each do |inquilino| %>
            <tr>
              <td><%= number_with_precision(inquilino.cedula, precision: 0, separator: ',', delimiter: '.') %></td>
              <td><%= inquilino.nombre %></td>
              <td><%= inquilino.apellido %></td>
              <td><%= number_with_precision(inquilino.telefono, precision: 0, separator: ',', delimiter: '.') %></td>
              <td><%= inquilino.email %></td>
              <% if inquilino.estado %>
                  <td class="text-center"><label class="label label-success">OCUPADO</label></td>
              <% else %>
                  <td class="text-center"><label class="label label-warning">DISPONIBLE</label></td>
              <% end %>
              <td><%= link_to 'VER', inquilino , class: "btn btn-info btn-xs" %></td>
              <td><%= link_to 'EDITAR', edit_inquilino_path(inquilino), class: "btn btn-warning btn-xs" %></td>
              <td><%= link_to 'ELIMINAR', inquilino, method: :delete, data: { confirm: 'ESTAS SEGURO?' } , class: "btn btn-danger btn-xs" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>
<%= link_to 'Nuevo Inquilino', new_inquilino_path ,class: 'btn btn-success btn-sm pull-left' %>

app/views/inquilinos/new.html.erb
<h1>Nuevo Inquilino</h1>

<%= render 'form' %>


<%= link_to glyph(:arrow_left) + ' ATRAS', inquilinos_path , class: "btn btn-default btn-xs"%>

app/views/inquilinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @inquilino.cedula %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @inquilino.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @inquilino.apellido %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @inquilino.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquilino.email %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @inquilino.estado %>
</p>



<%= link_to glyph(:pencil) + 'Editar', edit_inquilino_path(@inquilino) , class: "btn btn-warning btn-xs" %> |

<%= link_to glyph(:arrow_left) + ' ATRAS', inquilinos_path , class: "btn btn-default btn-xs"%>