config/routes.rb
Rails.application.routes.draw do

  resources :inquilinos
  resources :inquilinos
  resources :inquilinos
  resources :mov_cajas
  resources :cajas
  resources :cajas
  resources :detalle_recibos
  resources :recibos
  resources :movimientos do
    collection do
      put :pagar
    end
  end
  resources :departamentos
  resources :contratos
  
  resources :inquilinos do
    collection do
      get :autocomplete_inquilino_nombre
    end
  end
  
  resources :edificios

  devise_for :usuario,  controllers: { sessions: "usuario/sessions", registrations: "usuario/registrations", passwords: "usuario/passwords"  }, :path_names => {:sign_in => 'login', :sign_up => 'registro', :sign_out => 'logout'}
  as :usuarios do
    get 'sign_in' => 'usuario/sessions#new', :as => :new_usuario_session_path
    get 'sign_up' => 'usuario/registrations#create', :as => :usuario_registration_path
    delete 'sign_out' => 'usuario/sessions#destroy', :as => :destroy_usuario_session_path
    get 'new' => 'usuario/sessions#destroy', :as => :new_usuario_password_path
  end

  cajaabierto = nil

  if cajaabierto != nil
    root 'contratos#index'
  else
    root 'cajas#new'
  end

end

app/models/contrato.rb
class Contrato < ActiveRecord::Base

	belongs_to :inquilino
	belongs_to :departamento

	has_many :movimientos
	has_many :recibos

	validates :inquilino_id,  presence: true
	validates :departamento_id,  presence: true


end

app/controllers/contratos_controller.rb
class ContratosController < ApplicationController
  before_action :set_contrato, only: [:show, :edit, :update, :destroy]

  # GET /contratos
  # GET /contratos.json
  def index
    @contratos = Contrato.all
  end

  # GET /contratos/1
  # GET /contratos/1.json
  def show
  end

  # GET /contratos/new
  def new
    @contrato = Contrato.new
  end

  # GET /contratos/1/edit
  def edit
  end

  def dynamic_edificios
    @edificios = Edificio.find(:all)
  end

  # POST /contratos
  # POST /contratos.json
  def create
    @contrato = Contrato.new(contrato_params)

    respond_to do |format|
      if @contrato.save
        @departamento = Departamento.find_by(id: @contrato.departamento_id)
        @departamento.update(estado: 1)
        @fecha = @contrato.inicio_contrato
        cantidadmeses= ((@contrato.fin_contrato.year * 12 + @contrato.fin_contrato.month) - (@contrato.inicio_contrato.year * 12 + @contrato.inicio_contrato.month))
        for i in 1..cantidadmeses do
          @movimiento = Movimiento.create(contrato_id: @contrato.id, cuota:i , monto: @contrato.departamento.precio , vencimiento: @fecha + 1.months , estado: 0)
          @fecha = @fecha + 1.months
        end
        @movimiento.save
        @contrato.update(fin_contrato: @fecha)
        format.html { redirect_to @contrato, notice: 'Contrato creado exitosamente.' }
        format.json { render :show, status: :created, location: @contrato }
      else
        format.html { render :new }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contratos/1
  # PATCH/PUT /contratos/1.json
  def update
    respond_to do |format|
      if @contrato.update(contrato_params)
        format.html { redirect_to @contrato, notice: 'Contrato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contrato }
      else
        format.html { render :edit }
        format.json { render json: @contrato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contratos/1
  # DELETE /contratos/1.json
  def destroy
    @contrato.destroy
    respond_to do |format|
      format.html { redirect_to contratos_url, notice: 'Contrato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contrato
      @contrato = Contrato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contrato_params
      params.require(:contrato).permit(:inquilino_id, :edificio_id, :departamento_id, :fecha_contrato, :inicio_contrato, :fin_contrato, :vencimiento, :imagen)
    end
end

app/helpers/contratos_helper.rb
module ContratosHelper
end

app/views/contratos/_form.html.erb
<div class="panel panel-primary ">
    <div class="panel-body">
        <%= form_for(@contrato)  do |f| %>
        <% if @contrato.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@contrato.errors.count, "error") %> prohibited this contrato from being saved:</h2>
            <ul>
                <% @contrato.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <div class="field">
          <%= f.label :inquilino_id, "Elige Inquilino" %><br>

          <% inquilinos_array = Inquilino.where(:estado => 0).map { |inquilino| [" #{inquilino.nombre},#{inquilino.apellido}", inquilino.id ] }  %>
          <%= f.select(:inquilino_id, options_for_select(inquilinos_array), {prompt: true}, {class: 'form-control input-sm '})  %>

        </div>

          <div class="field">
                <%= f.label :departamento_id, "Elige un Edificio con su departamento y su precio" %><br>
            <% departamentos_array = Departamento.where(:estado => 0).map { |departamento| [" #{departamento.edificio.nombre_edificio} , #{departamento.nombre_departamento} , #{departamento.precio} ", departamento.id ] }  %>
            <%= f.select(:departamento_id, options_for_select(departamentos_array), {prompt: true}, {class: 'form-control input-sm '})  %>
        </div>

    
        <div class="hidden">
            <%= f.label :fecha_contrato %><br>
            <%= f.date_select :fecha_contrato , class: "form-control input-sm  "%>
        </div>
        
        <div class="field">
            <%= f.label :inicio_contrato %><br>
            <%= f.date_select :inicio_contrato , class: "form-control input-sm  " %>
        </div>

          <div class="field">
            <%= f.label :fin_contrato %><br>
            <%= f.date_select :fin_contrato , class: "form-control input-sm  " %>
          </div>
          <br>

          <div class="field">
            <%= f.label :imagen %><br>
            <%= f.file_field :imagen , class: "form-control input-sm  " %>
          </div>
          <br>

          <div class="text-left">
            <%= button_tag(type: 'submit', class: "btn btn-info btn-sm") do %>
                CREAR CONTRATO
            <% end %>
          </div>
        <% end %>
    </div>
</div>

app/views/contratos/edit.html.erb
<h1>Editar Contrato</h1>

<%= render 'form' %>

<%= link_to glyph(:eye_open) + 'VER', @contrato %> |
<%= link_to 'Back', contratos_path %>

app/views/contratos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h1 class="panel-title">Lista de Contratos </h1>
        </div>
        <div class="panel-body">
             <table id="tabla" class="table table-striped table-hover" width="100%">
                <thead>
                <tr>
      <th>Inquilino</th>
      <th>Departamento</th>
      <th>Precio del DPTO</th>
      <th>Fecha contrato</th>
      <th>Inicio contrato</th>
      <th>Fin contrato</th>
                  <th>Imagen</th>
      <th>Ver</th>
      <th>Editar</th>
      <th>Eliminar</th>
      
    </tr>
  </thead>

  <tbody>
    <% @contratos.each do |contrato| %>
      <tr>
        <td><%= contrato.inquilino.nombre %> <%= contrato.inquilino.apellido %></td>
        <td><%= contrato.departamento.nombre_departamento %></td>
        <td><%= number_with_precision(contrato.departamento.precio, precision: 0, separator: ',', delimiter: '.') %></td>
        <td><%= contrato.fecha_contrato.strftime("%d/%m/%Y") %></td>
        <td><%= contrato.inicio_contrato.strftime("%d/%m/%Y") %></td>
        <td><%= contrato.fin_contrato.strftime("%d/%m/%Y") %></td>
        <td><%= contrato.imagen %></td>
        <td><%= link_to 'VER', contrato , class: "btn btn-info btn-xs" %></td>
        <td><%= link_to 'EDITAR', edit_contrato_path(contrato), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'ELIMINAR', contrato, method: :delete, data: { confirm: 'ESTAS SEGURO?' } , class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Contrato', new_contrato_path ,class: 'btn btn-success btn-sm pull-left' %>

app/views/contratos/new.html.erb
<h1>Nuevo Contrato</h1>

<%= render 'form' %>


<%= link_to glyph(:arrow_left) + ' ATRAS', contratos_path , class: "btn btn-default btn-xs"%>

app/views/contratos/show.html.erb
<%= link_to glyph(:pencil) +'EDITAR', edit_caja_path(@contrato) ,class: "btn btn-warning btn-xs" %> |

<%= link_to glyph(:arrow_left) + ' ATRAS', contrato_path , class: "btn btn-default btn-xs"%>

<div class="col-xs-12">
    <div class="invoice-title">
        <h2>CONTRATO</h2>
        <h3 class="pull-right"> NUMERO CONTRATO: 00<%= @contrato.id %></h3>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-xs-12">
            <address>
                <strong>INQUILINO:</strong>
                <%= @contrato.inquilino.nombre %>
                <%= @contrato.inquilino.apellido %> <br>
            </address>
        </div>
        <div class="col-lg-4 col-md-4 col-xs-12 ">
            <address>
                <strong>DEPARTAMENTO:</strong>
                <%= @contrato.departamento.nombre_departamento %>
            </address>
            <address>
                <strong> NOMBRE DEL EDIFICIO</strong>
                 <%= @contrato.departamento.edificio.nombre_edificio %>
            </address>
        </div>
       <div class="col-lg-4 col-md-4 col-xs-12">
            <address>
                <strong>FECHA CONTRATO:</strong>
                <%= @contrato.fecha_contrato.strftime("%d/%m/%Y") %><br><br>
            </address>
            <address>
                <strong>FIN CONTRATO:</strong>
                <%= @contrato.fin_contrato.strftime("%d/%m/%Y") %><br><br>
            </address>
        </div>
    </div>
</div>
</div>
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><strong>DETALLES DEL CONTRATO</strong></h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
              <%= form_tag pagar_movimientos_path, method: :put  do %>
                <table class="table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                            <td></td>
                            <td class="text-center"><strong>CUOTA</strong></td>
                            <td class="text-center"><strong>MONTO</strong></td>
                            <td class="text-center"><strong>VENCIMIENTO</strong></td>
                            <td class="text-center"><strong>ESTADO</strong></td>
                        </tr>
                    </thead>
                    <tbody>
                            <%  @contrato.movimientos.each do |movimiento| %>
                        <tr>
                            <td><%= check_box_tag "movimientos_id[]", movimiento.id %></td>
                            <td class="text-center"><%= movimiento.cuota %></td>
                            <td class="text-center"><%= number_with_precision(movimiento.monto, precision: 0, separator: ',', delimiter: '.') %></td>
                            <td class="text-center"><%= movimiento.vencimiento.strftime("%d/%m/%Y") %></td>
                            <% if movimiento.estado %>
                              <td class="text-center"><label class="label label-success">Pagado</label></td>
                            <% else %>
                              <td class="text-center"><label class="label label-warning">Pendiente</label></td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                  <div class="text-left">
                    <%= button_tag(type: 'submit_tag', class: "btn btn-primary btn-sm") do %>
                        PAGAR CUOTAS SELECCIONADAS
                    <% end %>
                  </div>
              <% end %>
            </div>
        </div>
    </div>
</div>