config/routes.rb
Rails.application.routes.draw do

  resources :inquilinos
  resources :inquilinos
  resources :inquilinos
  resources :mov_cajas
  resources :cajas
  resources :cajas
  resources :detalle_recibos
  resources :recibos
  resources :movimientos do
    collection do
      put :pagar
    end
  end
  resources :departamentos
  resources :contratos
  
  resources :inquilinos do
    collection do
      get :autocomplete_inquilino_nombre
    end
  end
  
  resources :edificios

  devise_for :usuario,  controllers: { sessions: "usuario/sessions", registrations: "usuario/registrations", passwords: "usuario/passwords"  }, :path_names => {:sign_in => 'login', :sign_up => 'registro', :sign_out => 'logout'}
  as :usuarios do
    get 'sign_in' => 'usuario/sessions#new', :as => :new_usuario_session_path
    get 'sign_up' => 'usuario/registrations#create', :as => :usuario_registration_path
    delete 'sign_out' => 'usuario/sessions#destroy', :as => :destroy_usuario_session_path
    get 'new' => 'usuario/sessions#destroy', :as => :new_usuario_password_path
  end

  cajaabierto = nil

  if cajaabierto != nil
    root 'contratos#index'
  else
    root 'cajas#new'
  end

end

app/models/caja.rb
class Caja < ActiveRecord::Base
  belongs_to :usuario
  has_many :mov_cajas
end

app/controllers/cajas_controller.rb
class CajasController < ApplicationController
  before_action :set_caja, only: [:show, :edit, :update, :destroy]

  # GET /cajas
  # GET /cajas.json
  def index
    @cajas = Caja.all
  end

  # GET /cajas/1
  # GET /cajas/1.json
  def show
  end

  # GET /cajas/new
  def new
    @caja = Caja.new
    @caja.usuario_id = current_usuario.id # SE OBTIENE EL USUARIO AUTOMATICAMENTE
  end

  # GET /cajas/1/edit
  def edit
    @caja.usuario_id = current_usuario.id # SE OBTIENE EL USUARIO AUTOMATICAMENTE
    @caja.estado = 1

  end

  # POST /cajas
  # POST /cajas.json
  def create
    @caja = Caja.new(caja_params)
    @caja.fecha_cierre = nil
    @caja.entrada = @caja.apertura
    @caja.cierre = @caja.apertura
    respond_to do |format|
      if @caja.save
        @mov_caja = MovCaja.create!(caja_id: @caja.id, concepto: 'Apertura de caja', ingreso: @caja.apertura, egreso: 0, saldo: @caja.apertura)
        format.html { redirect_to @caja, notice: 'CAJA ABIERTO CORRECTAMENTE.' }
        format.json { render :show, status: :created, location: @caja }
      else
        format.html { render :new }
        format.json { render json: @caja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cajas/1
  # PATCH/PUT /cajas/1.json
  def update
    respond_to do |format|

      @caja.fecha_cierre = Time.now
      if @caja.update(caja_params)
        format.html { redirect_to @caja, notice: 'LA CAJA FUE CERRADA CORRECTAMENTE.' }
        format.json { render :show, status: :ok, location: @caja }
      else
        format.html { render :edit }
        format.json { render json: @caja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cajas/1
  # DELETE /cajas/1.json
  def destroy
    @caja.destroy
    respond_to do |format|
      format.html { redirect_to cajas_url, notice: 'Caja was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caja
      @caja = Caja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caja_params
      params.require(:caja).permit(:usuario_id, :fecha_cierre, :apertura, :cierre, :entrada, :salida, :estado)
    end
end

app/helpers/cajas_helper.rb
module CajasHelper
end

app/views/cajas/_form.html.erb
<center>
<%= form_for(@caja) do |f| %>
  <% if @caja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caja.errors.count, "error") %> prohibited this caja from being saved:</h2>

      <ul>
      <% @caja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h1>este es el form de caja</h1>
  <div class="hidden">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="hidden">
    <%= f.label :fecha_cierre %><br>
    <%= f.datetime_select :fecha_cierre %>
  </div>
  <div class="field">
    <%= f.label :apertura %><br>
    <%= f.number_field :apertura %>
  </div>
  <div class="hidden">
    <%= f.label :cierre %><br>
    <%= f.number_field :cierre %>
  </div>
  <div class="hidden">
    <%= f.label :entrada %><br>
    <%= f.number_field :entrada %>
  </div>
  <div class="hidden">
    <%= f.label :salida %><br>
    <%= f.number_field :salida %>
  </div>
  <div class="hidden">
    <%= f.label :estado %><br>
    <%= f.check_box :estado %>
  </div>
    <br>
    <div class="text-center">
      <%= button_tag(type: 'submit', class: "btn btn-info btn-sm") do %>
          CREAR CAJA
      <% end %>
    </div>
<% end %>
  </center>

app/views/cajas/_formedit.html.erb
<%= form_for(@caja) do |f| %>
  <% if @caja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caja.errors.count, "error") %> prohibited this caja from being saved:</h2>

      <ul>
      <% @caja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h1>EDIT</h1>
  <div class="hidden">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
    <div class="field">
      <%= f.label "fecha apertura" %><br>
      <%= f.datetime_select :created_at , readonly: "true" %>
    </div>

  <div class="field">
    <%= f.label :fecha_cierre %><br>
    <%= f.datetime_select :fecha_cierre ,  readonly: "true"%>
  </div>

  <div class="field">
    <%= f.label :apertura %><br>
    <%= f.number_field :apertura , readonly: "true"%>
  </div>
  <div class="field">
    <%= f.label :cierre %><br>
    <%= f.number_field :cierre , readonly: "true" %>
  </div>
  <div class="field">
    <%= f.label :entrada %><br>
    <%= f.number_field :entrada , readonly: "true"%>
  </div>
  <div class="field">
    <%= f.label :salida %><br>
    <%= f.number_field :salida , readonly: "true"%>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.check_box :estado , readonly: "true"%>
  </div>

      <div class="text-left">
        <%= button_tag(type: 'submit', class: "btn btn-warning btn-sm") do %>
            CERRAR CAJA
        <% end %>
      </div>
    <BR>

<% end %>

app/views/cajas/edit.html.erb
<h1>Editar Caja</h1>

<%= render 'formedit' %>



<%= link_to glyph(:eye_open) + 'VER', @caja,  class: "btn btn-info btn-xs" %> ||

<%= link_to glyph(:arrow_left) + ' ATRAS', cajas_path , class: "btn btn-default btn-xs"%>

app/views/cajas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="panel-title">LISTA DE  CAJAS </h1>
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table id="tabla" class="table table-bordered table-hover table-striper table-condensed" width="100%">
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Fecha cierre</th>
      <th>Monto Apertura</th>
      <th>Monto Cierre</th>
      <th>Monto Entrada</th>
      <th>Monto Salida</th>
      <th>Estado</th>
      <th CLASS="text-center" COLSPAN="3">ACCIONES</th>


    </tr>
  </thead>

  <tbody>
    <% @cajas.each do |caja| %>
      <tr>
        <td><%= caja.usuario_id %></td>
        <td><%= caja.fecha_cierre %></td>
        <td><%= number_with_precision(caja.apertura, precision: 0, separator: ',', delimiter: '.') %></td>
        <td><%= number_with_precision(caja.cierre, precision: 0, separator: ',', delimiter: '.') %></td>
        <td><%= number_with_precision(caja.entrada, precision: 0, separator: ',', delimiter: '.') %></td>
        <td><%= number_with_precision(caja.salida, precision: 0, separator: ',', delimiter: '.') %></td>
        <% if caja.estado %>
            <td class="text-center"><label class="label label-default">CERRADO</label></td>
        <% else %>
            <td class="text-center"><label class="label label-success">ABIERTO</label></td>
        <% end %>
        <td><%= link_to 'VER', caja  , class: "btn btn-info btn-xs"%></td>

        <% if caja.estado %>
        <td></td>
        <% else %>
            <td><%= link_to 'CERRAR CAJA', edit_caja_path(caja), class: "btn btn-warning btn-xs" %></td>
        <% end %>
        <td><%= link_to 'ELIMINAR CAJA', caja,class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'Nueva Caja', new_caja_path  ,class: 'btn btn-success btn-sm pull-left'%>

app/views/cajas/new.html.erb
<center><div class="page-header">

    <h1>Nueva Caja</h1>

</div>
<%= render 'form' %>

<br>
<%= link_to glyph(:arrow_left) + ' ATRAS', cajas_path , class: "btn btn-default btn-xs"%>

</CENTER>

app/views/cajas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-12">
  <div class="invoice-title">
    <h2>CAJA</h2>
    <h3 class="pull-right"> NUMERO DE CAJA: 00<%= @caja.id %></h3>
  </div>
  <hr>
  <div class="row">
    <div class="col-lg-3 col-md-3 col-xs-12">
      <address>
        <strong>USUARIO:</strong><br>
        <%= @caja.usuario.email %>
      </address>
      <address>
        <strong>ESTADO:</strong><br>
        <% if @caja.estado  %>
            <label class="text-danger">  CERRADO </label>
          <% else  %>
            <label class="text-success"> ABIERTO </label>
        <% end  %>
      </address>
    </div>
    <div class="col-lg-3 col-md-3 col-xs-12">
      <address>
        <strong>FECHA DE APERTURA:</strong><br>
         <%= @caja.created_at.strftime("%d/%m/%Y") %>
      </address>
      <address>
        <strong> FECHA DE CIERRE</strong><br>
         <%= @caja.fecha_cierre %>
      </address>
    </div>
    <div class="col-lg-3 col-md-3 col-xs-12">
      <address>
        <strong>MONTO DE APERTURA:</strong><br>
        <%= number_with_precision( @caja.apertura, precision: 0, separator: ',', delimiter: '.')%><br>

      </address>
      <address>
        <strong>MONTO DE CIERRE:</strong><br>
        <%= number_with_precision( @caja.cierre, precision: 0, separator: ',', delimiter: '.')%><br>
      </address>
    </div>
    <div class="col-lg-3 col-md-3 col-xs-12">
      <address>
        <strong>MONTO DE ENTRADA:</strong><br>
        <%= number_with_precision( @caja.entrada, precision: 0, separator: ',', delimiter: '.')%><br>
      </address>
      <address>
        <strong>MONTO DE SALIDA:</strong><br>
        <%= number_with_precision( @caja.salida, precision: 0, separator: ',', delimiter: '.')%><br>

      </address>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><strong>DETALLES DE LA CAJA</strong></h3>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-hover" width="100%">
          <thead>
          <tr>
            <th>Caja</th>
            <th>Concepto</th>
            <th>Ingreso</th>
            <th>Egreso</th>
            <th>Saldo</th>
            <th></th>
            <th></th>
          </tr>
          </thead>

            <tbody>
                <%  @caja.mov_cajas.each do |mov_caja| %>
                <tr>
                  <td><%= mov_caja.caja_id %></td>
                  <td><%= mov_caja.concepto %></td>
                  <td> <%= number_with_precision( mov_caja.ingreso, precision: 0, separator: ',', delimiter: '.')%></td>
                  <td> <%= number_with_precision( mov_caja.egreso, precision: 0, separator: ',', delimiter: '.')%></td>
                  <td> <%= number_with_precision( mov_caja.saldo, precision: 0, separator: ',', delimiter: '.')%></td>
                  <td><%= link_to 'VER', mov_caja , class: "btn btn-info btn-xs" %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
</div>
      </div>
    </div>
  </div>

      <%= link_to glyph(:pencil) +'EDITAR', edit_caja_path(@caja) ,class: "btn btn-warning btn-xs" %> |

      <%= link_to glyph(:arrow_left) + ' ATRAS', caja_path , class: "btn btn-default btn-xs"%>